const anx1Queries = {
    table4: {
        save4: `INSERT INTO ANX1_4 (DOCREF,
        ETIN ,LGL_TRDNAME ,SUPPLY_VAL ,SUPPLY_VAL_RETURNED,
        NET_SUPPLY_VAL, SUPPLY_TYPE , CGST,IGST,SGST ,CESS ,UPLOAD_DATE ,FP ,
        TAX_PERIOD ,STATUS ,FLAG ,ERROR_CODE ,ERROR_DETAIL) VALUES
        (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
        getTab4details: `SELECT * FROM ANX1_4 WHERE TAX_PERIOD=? AND FLAG NOT IN ('F') ORDER BY DOC_ID DESC`,
        getTab4detailsErr: `SELECT * FROM ANX1_4 WHERE TAX_PERIOD=? AND FLAG IN ('F' ,'C') ORDER BY DOC_ID DESC`,
        getTab4ByDocIds: `SELECT DOC_ID as docId,DOCREF FROM ANX1_4 where DOC_ID IN`,
        deleteTab4ByDocIds: `DELETE FROM ANX1_4 WHERE DOC_ID IN`,
        editTab4: `UPDATE ANX1_4 SET DOCREF =?,
    ETIN =? ,LGL_TRDNAME =? ,SUPPLY_VAL =? ,SUPPLY_VAL_RETURNED =?,
    NET_SUPPLY_VAL =?,  CGST =?,IGST=?,SGST =?,CESS =?,
 STATUS =?,FLAG =? , UPLOAD_DATE=?,ERROR_CODE =? , ERROR_DETAIL = ? WHERE DOC_ID =?`,
        calculate4Summ: 'select count(*) as noRec,(CASE WHEN SUM(SUPPLY_VAL) IS NULL THEN 0 ELSE SUM(SUPPLY_VAL) END) as supVal,(CASE WHEN SUM(SUPPLY_VAL_RETURNED) IS NULL THEN 0 ELSE SUM(SUPPLY_VAL_RETURNED) END) as suprVal, (CASE WHEN SUM(NET_SUPPLY_VAL) IS NULL THEN 0 ELSE SUM(NET_SUPPLY_VAL) END) as netVal, SUM(IGST) as igst, SUM(CGST) as cgst, SUM(SGST) as sgst, SUM(CESS) as cess from ANX1_4 where FLAG NOT IN ("D","F") and FP = ? and TAX_PERIOD = ?',
        calculate4ErrSumm: 'select count(*) as noRec,(CASE WHEN SUM(SUPPLY_VAL) IS NULL THEN 0 ELSE SUM(SUPPLY_VAL) END) as supVal,(CASE WHEN SUM(SUPPLY_VAL_RETURNED) IS NULL THEN 0 ELSE SUM(SUPPLY_VAL_RETURNED) END) as suprVal, (CASE WHEN SUM(NET_SUPPLY_VAL) IS NULL THEN 0 ELSE SUM(NET_SUPPLY_VAL) END) as netVal, SUM(IGST) as igst, SUM(CGST) as cgst, SUM(SGST) as sgst, SUM(CESS) as cess from ANX1_4 where FLAG ="C" and FP = ? and TAX_PERIOD = ?',
        getCountMarkForDelfor4: 'select count(*) as count from ANX1_4 where FLAG = "D" and FP= ? and TAX_PERIOD = ?',
        getCountYetToCorrectForDelfor4: 'select count(*) as count from ANX1_4 where FLAG = "F" and FP= ? and TAX_PERIOD = ?',
        save4summ: 'INSERT INTO ANX1_SUMM (TABLE_TYP, NO_OF_REC, DOC_TYPE, CTIN, LGL_TRDNAME,  FP, TAX_PERIOD, NET_TAXABLE_VALUE, IGST, CGST, SGST, CESS, PAYMT_WITH_TAX, NO_OF_REC_REJ, NO_OF_REC_MFD, VAL_SUP_MADE, VAL_SUP_RETURN , SUMM_TYP) VALUES ',
        save4Errsumm: 'INSERT INTO ANX1_ERR_SUMM (TABLE_TYP, NO_OF_REC, DOC_TYPE, CTIN, LGL_TRDNAME,  FP, TAX_PERIOD, NET_TAXABLE_VALUE, IGST, CGST, SGST, CESS, PAYMT_WITH_TAX, NO_OF_REC_REJ, NO_OF_REC_MFD, VAL_SUP_MADE, VAL_SUP_RETURN , SUMM_TYP) VALUES ',
        delete4summ: 'DELETE from ANX1_SUMM where FP= ? and TAX_PERIOD = ? and TABLE_TYP = ?',
        delete4Errsumm: 'DELETE from ANX1_ERR_SUMM where FP= ? and TAX_PERIOD = ? and TABLE_TYP = ?',
        get4Summ: 'select DOC_TYPE as doctyp , NO_OF_REC as records, ROUND(NET_TAXABLE_VALUE, 2) as nsup, ROUND(IGST, 2) as igst, ROUND(CGST, 2) as cgst, ROUND(SGST, 2) as sgst, ROUND(CESS, 2) as cess, NO_OF_REC_MFD as mfd , VAL_SUP_MADE as sup, VAL_SUP_RETURN as supr from ANX1_SUMM WHERE FP= ? and TAX_PERIOD = ? and TABLE_TYP = ?',
        get4ErrJson : "SELECT * FROM ANX1_4 WHERE TAX_PERIOD=? AND FLAG IN ('C','F')",
        getTab4json: "SELECT * FROM ANX1_4 WHERE TAX_PERIOD=? AND FLAG NOT IN ('U','F')",
    },
    table4Err : {
      get4Summ: 'select DOC_TYPE as doctyp , NO_OF_REC as records, ROUND(NET_TAXABLE_VALUE, 2) as nsup, ROUND(IGST, 2) as igst, ROUND(CGST, 2) as cgst, ROUND(SGST, 2) as sgst, ROUND(CESS, 2) as cess, NO_OF_REC_MFD as mfd , VAL_SUP_MADE as sup, VAL_SUP_RETURN as supr from ANX1_ERR_SUMM WHERE FP= ? and TAX_PERIOD = ? and TABLE_TYP = ?',
    },
    table3i: {
        save3i: `
          INSERT INTO ANX1_3I (
            DOCREF , 
            POS ,
            TAX_VALUE ,
            IGST , 
            CESS ,
            SUPPLY_TYPE ,
            UPLOAD_DT,
            DIFF_PERCENTAGE ,
            REFUND_ELG, 
            FLAG, 
            STATUS, 
            FP,
            TAX_PERIOD,
            ERROR_CODE,
            ERROR_DETAIL 
          ) VALUES
          (
            ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?
          )
          `,
        getAll3i: `Select  DOC_ID as docId,
                    DOCREF as docref, 
                    POS as pos,
                    TAX_VALUE as taxVal,
                    IGST as igst, 
                    CESS as cess,
                    SUPPLY_TYPE as suptype,
                    UPLOAD_DT as upldt,
                    DIFF_PERCENTAGE as diffpercnt,
                    REFUND_ELG as rfndelg, 
                    FLAG as flag, 
                    STATUS as status, 
                    FP as fp,
                    TAX_PERIOD as taxPrd
                     from ANX1_3I WHERE TAX_PERIOD=? AND FLAG NOT IN ('F') ORDER BY DOC_ID DESC`,
          getAll3iErr: `Select  DOC_ID as docId,
                     DOCREF as docref, 
                     POS as pos,
                     TAX_VALUE as taxVal,
                     IGST as igst, 
                     CESS as cess,
                     SUPPLY_TYPE as suptype,
                     UPLOAD_DT as upldt,
                     DIFF_PERCENTAGE as diffpercnt,
                     REFUND_ELG as rfndelg, 
                     FLAG as flag, 
                     STATUS as status, 
                     FP as fp,
                     TAX_PERIOD as taxPrd ,
                     ERROR_CODE as err_cd,
                     ERROR_DETAIL as err_msg
                      from ANX1_3I WHERE TAX_PERIOD=? AND FLAG IN ('C','F') ORDER BY DOC_ID DESC`,
        getTab3iByDocIds: `SELECT DOC_ID as docId,DOCREF as docref FROM ANX1_3I where DOC_ID IN`,
        deleteTab3iByDocIds: `DELETE FROM ANX1_3I WHERE DOC_ID IN`,
    edit3i :`UPDATE ANX1_3I SET  
    DOCREF =?, 
    POS =? ,
    TAX_VALUE =? ,
    IGST = ?, 
    CESS = ?,
    FLAG =?, 
    STATUS =? ,UPLOAD_DT=?, ERROR_CODE=? ,ERROR_DETAIL=? WHERE DOC_ID =?`,
    calculate3iSumm:'select count(*) as noRec, (CASE WHEN SUM(TAX_VALUE) IS NULL THEN 0 ELSE SUM(TAX_VALUE) END) as totVal, SUM(IGST) as igst, SUM(CESS) as cess from ANX1_3I where FLAG NOT IN ("D","F") and FP = ? and TAX_PERIOD = ?',
    getCountMarkForDelfor3i:'select count(*) as count from ANX1_3I where FLAG = "D" and FP= ? and TAX_PERIOD = ?',
    get3iDetailsByDocRef: `SELECT * FROM ANX1_3I where DOCREF = ?`,
    update3iDetailsByDocRef: `UPDATE ANX1_3I SET TAX_VALUE= ?,IGST=?,CESS= ? where DOCREF = ?`,
    updateItemDetails: `update ANX1_ITEMDTLS set
    HSN =?,
    TAXRATE=?,
    TAXVAL=?,
    IGST =? ,
    CGST=?,
    SGST =?,
    CESS=?,
    ITEMREF=? 
    where ITEM_ID = ?`,
    saveItemDetailsBatch :`INSERT INTO ANX1_ITEMDTLS (HSN, TAXRATE, TAXVAL, IGST, CGST, SGST, CESS, ITEMREF) VALUES`,
    get3IjSON: `SELECT * FROM ANX1_3I as a, ANX1_ITEMDTLS AS b where b.ITEMREF = a.DOCREF AND a.FLAG NOT IN ('U','F') and a.TAX_PERIOD=? order by a.DOC_ID`,
    get3IErrJson : "SELECT * FROM ANX1_3I as a, ANX1_ITEMDTLS AS b where b.ITEMREF = a.DOCREF AND a.FLAG IN ('C','F') AND a.TAX_PERIOD=? order by a.DOC_ID",
    update3iFlagByDocRef: `UPDATE ANX1_3I SET FLAG = 'C', ERROR_CODE='', ERROR_DETAIL='' where DOCREF = ?`,
  }  ,
  table3j:{
    save3j : `INSERT INTO ANX1_3J(DOCREF,DOCTYPE,POS,BOENUM,BOEPCD,BOEDT,BOEVAL,
      BOEYEAR,TAX_VALUE,IGST,CESS,SUPPLY_TYPE,UPLOAD_DT,REFUND_ELG,FLAG,STATUS,FP,TAX_PERIOD ,ERROR_CODE ,ERROR_DETAIL) 
      VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
    update3j :`UPDATE ANX1_3J SET DOCREF=?,DOCTYPE=?,
    POS =?,BOENUM=?,BOEPCD=?,BOEDT=?,BOEVAL=?,BOEYEAR=?,TAX_VALUE=?,IGST=?,CESS=?,
    SUPPLY_TYPE=?,REFUND_ELG=?,FLAG=?,STATUS=? , UPLOAD_DT=?,ERROR_CODE=? ,ERROR_DETAIL=? WHERE DOC_ID=?`,
    calculate3jSumm:'select count(*) as noRec, (CASE WHEN SUM(TAX_VALUE) IS NULL THEN 0 ELSE SUM(TAX_VALUE) END) as totVal, SUM(IGST) as igst, SUM(CESS) as cess from ANX1_3J where FLAG NOT IN ("D","F") and FP = ? and TAX_PERIOD = ?',
    calculate3jErrSumm:'select count(*) as noRec, (CASE WHEN SUM(TAX_VALUE) IS NULL THEN 0 ELSE SUM(TAX_VALUE) END) as totVal, SUM(IGST) as igst, SUM(CESS) as cess from ANX1_3J where FLAG ="C" and FP = ? and TAX_PERIOD = ?',
    getCountMarkForDelfor3j:'select count(*) as count from ANX1_3J where FLAG = "D" and FP= ? and TAX_PERIOD = ?',
    getCountYetToCorrectfor3j:'select count(*) as count from ANX1_3J where FLAG = "F" and FP= ? and TAX_PERIOD = ?',
    getAll3j: `Select  DOC_ID as docid,
                    DOCREF as docref, 
                    POS as pos,
                    TAX_VALUE as taxVal,
                    IGST as igst, 
                    CESS as cess,
                    SUPPLY_TYPE as suptype,
                    UPLOAD_DT as upldt,
                    REFUND_ELG as rfndelg, 
                    FLAG as flag, 
                    STATUS as status, 
                    FP as fp,
                    TAX_PERIOD as taxPrd,
                    BOENUM as num,
                    BOEPCD as pcode,
                    BOEDT as dt,
                    BOEVAL as val
                     from ANX1_3J WHERE TAX_PERIOD=? AND FLAG NOT IN ('F') ORDER BY DOC_ID DESC`,
                     getAll3jErr: `Select  DOC_ID as docid,
                     DOCREF as docref, 
                     POS as pos,
                     TAX_VALUE as taxVal,
                     IGST as igst, 
                     CESS as cess,
                     SUPPLY_TYPE as suptype,
                     UPLOAD_DT as upldt,
                     REFUND_ELG as rfndelg, 
                     FLAG as flag, 
                     STATUS as status, 
                     FP as fp,
                     TAX_PERIOD as taxPrd,
                     BOENUM as num,
                     BOEPCD as pcode,
                     BOEDT as dt,
                     BOEVAL as val,
                     ERROR_CODE as err_cd,
                     ERROR_DETAIL as err_msg
                    from ANX1_3J WHERE TAX_PERIOD=? AND FLAG IN ('C','F') ORDER BY DOC_ID DESC`,
                     getTab3jByDocIds: `SELECT DOC_ID as docid,DOCREF as docref FROM ANX1_3J where DOC_ID IN`,
                     deleteTab3jByDocIds: `DELETE FROM ANX1_3J WHERE DOC_ID IN`,
                     get3jDetailsByDocRef: `SELECT * FROM ANX1_3J where DOCREF = ?`,
                     update3jDetailsByDocRef: `UPDATE ANX1_3J SET TAX_VALUE= ?,IGST=?,CESS= ? where DOCREF = ?`,
                     update3jFlagByDocRef: `UPDATE ANX1_3J SET FLAG = 'C' where DOCREF = ?`,
                     get3jDetailsByDocRef: `SELECT * FROM ANX1_3J where DOCREF = ?`,
                     get3jjSON: `SELECT * FROM ANX1_3J as a, ANX1_ITEMDTLS AS b where b.ITEMREF = a.DOCREF AND a.FLAG NOT IN ('U','F') and a.TAX_PERIOD=? order by a.POS, a.DOC_ID`,
                     get3JErrJson : "SELECT * FROM ANX1_3J as a, ANX1_ITEMDTLS AS b where b.ITEMREF = a.DOCREF AND a.FLAG IN ('C','F') AND a.TAX_PERIOD=? order by a.POS, a.DOC_ID"
  }
  }

   


module.exports = {
    anx1Queries: anx1Queries
}