const VERSION_HISTORY = ["beta_v0.1", "beta_v0.2", "beta_v0.3", "beta_v0.4", "beta_v0.5", "beta_v0.6"];

const vScript = {
  "v001": {
    offlinedb: [],
    gstindb: [
      "ALTER TABLE MR_DETL ADD COLUMN FIELD_REFINE_MATCH TEXT"
    ],
    desc: "use this when moving from beta_v0.1 to beta_v0.2 version"
  },
  "v002": {
    offlinedb: [],
    gstindb: [
      "CREATE TABLE IF NOT EXISTS ANX1_3L (DOC_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, TABLE_TYPE TEXT NOT NULL, DOCREF TEXT NOT NULL, CTIN  TEXT (15) NOT NULL,LGL_TRDNAME TEXT (99), DOCTYPE CHAR(2) NOT NULL,DOC_NUM TEXT(16) NOT NULL,DOC_DATE DATE NOT NULL,DOC_YEAR TEXT(4) NOT NULL,DOC_VAL DECIMAL (13, 2) NOT NULL, POS STRING (2) NOT NULL, DIFF_PERCENTAGE INTEGER, SEC7_ACT CHAR(1), TAX_VALUE DECIMAL (15, 2) NOT NULL, IGST  DECIMAL (13, 2),CGST  DECIMAL (13, 2), SGST  DECIMAL (13, 2), CESS  DECIMAL (13, 2), SUPPLY_TYPE TEXT NOT NULL, CLAIM_REFUND CHAR(1), UPLOAD_DT TEXT, FLAG CHAR(1) NOT NULL,  STATUS TEXT, FP TEXT, TAX_PERIOD TEXT, ERROR_CODE TEXT, ERROR_DETAIL TEXT, CONSTRAINT UNIQUE_ANX1_3L UNIQUE (TABLE_TYPE,DOC_NUM COLLATE NOCASE,DOCTYPE,DOC_YEAR,TAX_PERIOD,FP));",
      "CREATE TABLE IF NOT EXISTS ANX1_ERR_SUMM (TABLE_TYP TEXT NOT NULL, NO_OF_REC INTEGER NOT NULL, DOC_TYPE CHAR(2), CTIN TEXT, LGL_TRDNAME TEXT,FP TEXT NOT NULL, TAX_PERIOD TEXT NOT NULL, NET_TAXABLE_VALUE DECIMAL (15, 2) NOT NULL,CGST DECIMAL (13, 2),IGST DECIMAL (13, 2),SGST DECIMAL (13, 2),CESS DECIMAL (13, 2), PAYMT_WITH_TAX CHAR(1), NO_OF_REC_REJ INTEGER, NO_OF_REC_MFD INTEGER, VAL_SUP_MADE DECIMAL (13, 2), VAL_SUP_RETURN DECIMAL (13, 2), SUMM_TYP TEXT DEFAULT NULL, CONSTRAINT UNIQUE_ANX1_ERR_SUMM UNIQUE (TABLE_TYP, FP, TAX_PERIOD, DOC_TYPE, CTIN));"
    ],
    desc: "use this when moving from beta_v0.2 to beta_v0.3 version"
  },
  "v003": {
    offlinedb: [],
    gstindb: [],
    desc: "use this when moving from beta_v0.3 to beta_v0.4 version"
  },
  "v004": {
    offlinedb: [],
    gstindb: [
      "CREATE TABLE IF NOT EXISTS FILE_UPLOAD_HISTORY(ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,TAX_PERIOD TEXT NOT NULL,FILE_NAME STRING NOT NULL, TYPE CHAR(1) NOT NULL, UPLOAD_TIME DATETIME NOT NULL, STATUS CHAR(1) NOT NULL, ERROR_FILE STRING, CONSTRAINT UNIQUE_FILE_UPLOAD_HISTORY UNIQUE (FILE_NAME, TAX_PERIOD));",
      "CREATE TABLE IF NOT EXISTS ANX1_3AA (DOC_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,DOCREF TEXT NOT NULL UNIQUE,PLACE_OF_SUPPLY INTEGER NOT NULL,DIFF_PERCENTAGE INTEGER,DOC_TYPE CHAR(1),SEC7_ACT CHAR(1),UPLOAD_DATE DATE,SUPPLY_TYPE TEXT NOT NULL,FP TEXT,TAX_PERIOD TEXT,TOTAL_TAXABLE_VALUE INTEGER NOT NULL,CGST INTEGER,IGST INTEGER,SGST INTEGER,CESS INTEGER,STATUS TEXT,FLAG CHAR(1),ERROR_CODE TEXT,ERROR_DETAIL TEXT,CONSTRAINT UNIQUE_ANX1_3AA UNIQUE (PLACE_OF_SUPPLY,SEC7_ACT ,DIFF_PERCENTAGE ,FP , TAX_PERIOD));",
      "CREATE TABLE IF NOT EXISTS ANX1_3CDA(DOC_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,DOC_TYPE CHAR NOT NULL,ODOC_TYPE CHAR NOT NULL,GSTIN TEXT NOT NULL,DOCREF TEXT NOT NULL,DOC_NUM TEXT NOT NULL,DOC_DATE DATE NOT NULL,ODOCREF TEXT,ODOC_NUM TEXT NOT NULL,ODOC_DATE DATE NOT NULL,ODOC_YEAR TEXT(4) NOT NULL,DOC_VAL DECIMAL(13,2) NOT NULL,DOC_YEAR TEXT(4) NOT NULL,EXPORT_TYPE VARCHAR2(6) NOT NULL,SHIPNG_BILL_NUM TEXT,SHIPNG_BILL_DATE DATE,PORT_CODE TEXT,TOTAL_TAX_VALUE DECIMAL (13, 2) NOT NULL,TOTAL_IGST  DECIMAL (13, 2),TOTAL_CESS  DECIMAL (13, 2),SUPPLY_TYPE TEXT NOT NULL,UPLOAD_DT DATE,FLAG CHAR(1) NOT NULL,STATUS TEXT,FP TEXT,TAX_PERIOD TEXT,ERROR_CODE TEXT,ERROR_DETAIL TEXT,CONSTRAINT UNIQUE_ANX1_3CDA UNIQUE (DOC_NUM COLLATE NOCASE,DOC_TYPE,DOC_YEAR,TAX_PERIOD,FP),CONSTRAINT UNIQUE2_ANX1_3CDA UNIQUE (ODOC_NUM COLLATE NOCASE,ODOC_TYPE,DOC_YEAR,TAX_PERIOD,FP));",
      "CREATE TABLE IF NOT EXISTS ANX1_3BAO (DOC_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,DOCREF TEXT NOT NULL,REVDOCREF TEXT NOT NULL,CTIN TEXT (15) NOT NULL, LGL_TRDNAME TEXT (99), DOCTYPE CHAR(2) NOT NULL,DOC_NUM TEXT(16) NOT NULL,DOC_DATE DATE NOT NULL, DOC_YEAR TEXT(4) NOT NULL, CTIN_TYPE TEXT, UPLOAD_DT TEXT, FLAG CHAR(1) NOT NULL, REV_CTIN  TEXT(15) NOT NULL, REV_LGL_TRDNAME TEXT(99), REV_DOCTYPE CHAR(2) NOT NULL, REV_DOC_NUM TEXT(16) NOT NULL,REV_DOC_DATE DATE NOT NULL,REV_DOC_YEAR TEXT(4) NOT NULL,REV_DOC_VAL DECIMAL (13, 2) NOT NULL, REV_POS STRING (2) NOT NULL, REV_DIFF_PERCENTAGE INTEGER NOT NULL, REV_SEC7_ACT CHAR(1),REV_TAX_VALUE DECIMAL (15, 2) NOT NULL, REV_CTIN_TYPE TEXT,REV_IGST  DECIMAL (13, 2), REV_CGST  DECIMAL (13, 2), REV_SGST  DECIMAL (13, 2), REV_CESS  DECIMAL (13, 2),REV_SUPPLY_TYPE TEXT NOT NULL,STATUS TEXT, FP TEXT NOT NULL, TAX_PERIOD TEXT NOT NULL, ERROR_CODE TEXT, ERROR_DETAIL TEXT, CONSTRAINT REV_UNIQUE_ANX1_3BAO UNIQUE (REV_DOC_NUM COLLATE NOCASE,REV_DOCTYPE,REV_DOC_YEAR,TAX_PERIOD,FP), CONSTRAINT ORG_UNIQUE_ANX1_3BAO UNIQUE(DOC_NUM COLLATE NOCASE,DOCTYPE,DOC_YEAR,TAX_PERIOD,FP));",
      "CREATE TABLE IF NOT EXISTS ANX1_3BA (DOC_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,DOCREF TEXT NOT NULL,REVDOCREF TEXT NOT NULL,CTIN TEXT (15) NOT NULL, LGL_TRDNAME TEXT (99), DOCTYPE CHAR(2) NOT NULL,DOC_NUM TEXT(16) NOT NULL,DOC_DATE DATE NOT NULL, DOC_YEAR TEXT(4) NOT NULL, CTIN_TYPE TEXT, UPLOAD_DT TEXT, FLAG CHAR(1) NOT NULL, REV_CTIN  TEXT(15) NOT NULL, REV_LGL_TRDNAME TEXT(99), REV_DOCTYPE CHAR(2) NOT NULL, REV_DOC_NUM TEXT(16) NOT NULL,REV_DOC_DATE DATE NOT NULL,REV_DOC_YEAR TEXT(4) NOT NULL,REV_DOC_VAL DECIMAL (13, 2) NOT NULL, REV_POS STRING (2) NOT NULL, REV_DIFF_PERCENTAGE INTEGER NOT NULL, REV_SEC7_ACT CHAR(1),REV_TAX_VALUE DECIMAL (15, 2) NOT NULL, REV_CTIN_TYPE TEXT,REV_IGST  DECIMAL (13, 2), REV_CGST  DECIMAL (13, 2), REV_SGST  DECIMAL (13, 2), REV_CESS  DECIMAL (13, 2),REV_SUPPLY_TYPE TEXT NOT NULL,STATUS TEXT, FP TEXT NOT NULL, TAX_PERIOD TEXT NOT NULL, ERROR_CODE TEXT, ERROR_DETAIL TEXT, CONSTRAINT REV_UNIQUE_ANX1_3BA UNIQUE (REV_DOC_NUM COLLATE NOCASE,REV_DOCTYPE,REV_DOC_YEAR,TAX_PERIOD,FP), CONSTRAINT ORG_UNIQUE_ANX1_3BA UNIQUE (DOC_NUM COLLATE NOCASE,DOCTYPE,DOC_YEAR,TAX_PERIOD,FP));",
      "CREATE TABLE IF NOT EXISTS ANX1_3EFA (DOC_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,DOCREF TEXT NOT NULL,CTIN TEXT (15) NOT NULL, LGL_TRDNAME TEXT (99), DOCTYPE CHAR(2) NOT NULL,DOC_NUM TEXT(16) NOT NULL,DOC_DATE DATE NOT NULL, DOC_YEAR TEXT(4) NOT NULL, CTIN_TYPE TEXT, UPLOAD_DT TEXT, FLAG CHAR(1) NOT NULL, REV_CTIN  TEXT(15) NOT NULL, REV_LGL_TRDNAME TEXT(99), REV_DOCTYPE CHAR(2) NOT NULL, REV_DOC_NUM TEXT(16) NOT NULL,REV_DOC_DATE DATE NOT NULL,REV_DOC_YEAR TEXT(4) NOT NULL,REV_DOC_VAL DECIMAL (13, 2) NOT NULL, REV_POS STRING (2) NOT NULL, REV_DIFF_PERCENTAGE INTEGER NOT NULL, REV_TAX_VALUE DECIMAL (15, 2) NOT NULL, REV_CTIN_TYPE TEXT,REV_IGST  DECIMAL (13, 2), REV_CESS  DECIMAL (13, 2),REV_SUPPLY_TYPE TEXT NOT NULL,PAY_TYP CHAR(6) NOT NULL,CLAIM_REFUND CHAR(1),STATUS TEXT, FP TEXT NOT NULL, TAX_PERIOD TEXT NOT NULL, ERROR_CODE TEXT, ERROR_DETAIL TEXT, CONSTRAINT REV_UNIQUE_ANX1_3EFA UNIQUE (REV_DOC_NUM COLLATE NOCASE,REV_DOCTYPE,REV_DOC_YEAR,TAX_PERIOD,FP), CONSTRAINT ORG_UNIQUE_ANX1_3EFA UNIQUE(DOC_NUM COLLATE NOCASE,DOCTYPE,DOC_YEAR,TAX_PERIOD,FP));",
      "CREATE TABLE IF NOT EXISTS ANX1_3GA (DOC_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,DOCREF TEXT NOT NULL,CTIN TEXT (15) NOT NULL, LGL_TRDNAME TEXT (99), DOCTYPE CHAR(2) NOT NULL,DOC_NUM TEXT(16) NOT NULL,DOC_DATE DATE NOT NULL, DOC_YEAR TEXT(4) NOT NULL, CTIN_TYPE TEXT, UPLOAD_DT TEXT, FLAG CHAR(1) NOT NULL, REV_CTIN  TEXT(15) NOT NULL, REV_LGL_TRDNAME TEXT(99), REV_DOCTYPE CHAR(2) NOT NULL, REV_DOC_NUM TEXT(16) NOT NULL,REV_DOC_DATE DATE NOT NULL,REV_DOC_YEAR TEXT(4) NOT NULL,REV_DOC_VAL DECIMAL (13, 2) NOT NULL, REV_POS STRING (2) NOT NULL, REV_DIFF_PERCENTAGE INTEGER NOT NULL, REV_SEC7_ACT CHAR(1),REV_TAX_VALUE DECIMAL (15, 2) NOT NULL, REV_CTIN_TYPE TEXT,REV_IGST  DECIMAL (13, 2), REV_CGST  DECIMAL (13, 2), REV_SGST  DECIMAL (13, 2), REV_CESS  DECIMAL (13, 2),CLAIM_REFUND CHAR(1),REV_SUPPLY_TYPE TEXT NOT NULL,STATUS TEXT, FP TEXT NOT NULL, TAX_PERIOD TEXT NOT NULL, ERROR_CODE TEXT, ERROR_DETAIL TEXT, CONSTRAINT REV_UNIQUE_ANX1_3DEA UNIQUE (REV_DOC_NUM COLLATE NOCASE,REV_DOCTYPE,REV_DOC_YEAR,TAX_PERIOD,FP), CONSTRAINT ORG_UNIQUE_ANX1_3GA UNIQUE (DOC_NUM COLLATE NOCASE,DOCTYPE,DOC_YEAR,TAX_PERIOD,FP));",
      "CREATE TABLE IF NOT EXISTS OTHER_MASTER(ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,RETURN_TYPE TEXT NOT NULL,FP TEXT,TAX_PERIOD TEXT,AMD_NUM INTEGER);",
      "CREATE TABLE IF NOT EXISTS ANX1_3HA(DOC_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,DOCREF TEXT NOT NULL,CTIN  TEXT (15) NOT NULL,LGL_TRDNAME TEXT (99),POS STRING (2) NOT NULL,TAX_VALUE DECIMAL (13, 2) NOT NULL,IGST  DECIMAL (13, 2),CGST  DECIMAL (13, 2),SGST  DECIMAL (13, 2),CESS  DECIMAL (13, 2),DIFF_PERCENTAGE INTEGER NOT NULL,SEC7_ACT CHAR(1) NOT NULL,SUPPLY_TYPE TEXT NOT NULL,UPLOAD_DT TEXT,REFUND_ELG CHAR(1) NOT NULL,FLAG CHAR(1) NOT NULL,STATUS TEXT,FP TEXT,DOCTYPE CHAR NOT NULL,TAX_PERIOD TEXT,ERROR_CODE TEXT,ERROR_DETAIL TEXT,CONSTRAINT UNIQUE_ANX1_3HA UNIQUE (POS,DIFF_PERCENTAGE,SEC7_ACT,CTIN,FP,TAX_PERIOD));",
      "CREATE TABLE IF NOT EXISTS ANX1_3IA(DOC_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,DOCREF TEXT NOT NULL,POS STRING (2) NOT NULL,TAX_VALUE DECIMAL (13, 2) NOT NULL,IGST  DECIMAL (13, 2),CESS  DECIMAL (13, 2),SUPPLY_TYPE TEXT NOT NULL,UPLOAD_DT TEXT,DIFF_PERCENTAGE INTEGER NOT NULL,REFUND_ELG CHAR(1) NOT NULL,FLAG CHAR(1) NOT NULL,STATUS TEXT,FP TEXT,TAX_PERIOD TEXT,ERROR_CODE TEXT,ERROR_DETAIL TEXT,CONSTRAINT UNIQUE_ANX1_3IA UNIQUE (POS,FP,TAX_PERIOD));",
      "CREATE TABLE IF NOT EXISTS ANX1_4A(DOC_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,DOCREF TEXT NOT NULL UNIQUE,ETIN TEXT NOT NULL,LGL_TRDNAME TEXT,SUPPLY_VAL DECIMAL (13, 2) NOT NULL,SUPPLY_VAL_RETURNED DECIMAL (13, 2)  NOT NULL,NET_SUPPLY_VAL DECIMAL (13, 2) NOT NULL,SUPPLY_TYPE TEXT,CGST DECIMAL (13, 2),IGST DECIMAL (13, 2),SGST DECIMAL (13, 2),CESS DECIMAL (13, 2),UPLOAD_DATE DATE,FP TEXT,TAX_PERIOD TEXT,STATUS TEXT,FLAG CHAR(1),ERROR_CODE TEXT,ERROR_DETAIL TEXT,CONSTRAINT UNIQUE_ANX1_4A UNIQUE (ETIN,TAX_PERIOD));",
      "CREATE TABLE IF NOT EXISTS ANX1_3JA(DOC_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,DOCREF TEXT NOT NULL,ODOCREF TEXT NOT NULL,ODOCTYPE CHAR NOT NULL,OBOENUM STRING(16) NOT NULL,OBOEDT DATE,OBOEPCD STRING(6),OBOEYEAR STRING(4) NOT NULL,DOCTYPE CHAR NOT NULL,POS STRING (2) NOT NULL,BOENUM STRING(16) NOT NULL,BOEPCD STRING(6),BOEDT DATE,BOEVAL DECIMAL(13,2) NOT NULL,BOEYEAR STRING(4) NOT NULL,TAX_VALUE DECIMAL (13, 2) NOT NULL,IGST  DECIMAL (13, 2),CESS  DECIMAL (13, 2),SUPPLY_TYPE TEXT NOT NULL,UPLOAD_DT TEXT,REFUND_ELG CHAR(1) NOT NULL,FLAG CHAR(1) NOT NULL,STATUS TEXT,FP TEXT,TAX_PERIOD TEXT,ERROR_CODE TEXT,ERROR_DETAIL TEXT,CONSTRAINT UNIQUE_ANX1_3JA UNIQUE(BOENUM COLLATE NOCASE,BOEYEAR,BOEPCD COLLATE NOCASE,TAX_PERIOD,FP)CONSTRAINT UNIQUE2_ANX1_3JA UNIQUE(OBOENUM COLLATE NOCASE,OBOEYEAR,OBOEPCD COLLATE NOCASE,TAX_PERIOD,FP));",
      "CREATE TABLE IF NOT EXISTS ANX1_3KA(DOC_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,DOCREF TEXT NOT NULL,ODOCREF TEXT NOT NULL,OCTIN TEXT (15) NOT NULL,OLGL_TRDNAME TEXT (99),ODOCTYPE CHAR(2) NOT NULL,OBOE_NUM TEXT(16) NOT NULL,OBOE_DATE DATE NOT NULL,OPORT_CODE TEXT(6) NOT NULL,OBOE_YEAR TEXT(4) NOT NULL,CTIN TEXT (15) NOT NULL,LGL_TRDNAME TEXT (99),DOCTYPE CHAR(2) NOT NULL,PORT_CODE TEXT(6) NOT NULL,BOE_NUM TEXT(16) NOT NULL,BOE_DATE DATE NOT NULL,BOE_YEAR TEXT(4) NOT NULL,BOE_VALUE DECIMAL(13, 2) NOT NULL,POS TEXT(2) NOT NULL,SUPPLY_TYPE TEXT NOT NULL,TAX_VALUE DECIMAL(15, 2) NOT NULL,IGST  DECIMAL(13, 2),CESS  DECIMAL(13, 2),UPLOAD_DT TEXT,FLAG CHAR(1) NOT NULL,STATUS TEXT,FP TEXT,TAX_PERIOD TEXT,ERROR_CODE TEXT,ERROR_DETAIL TEXT,CONSTRAINT UNIQUE_ANX1_3KA UNIQUE(BOE_NUM COLLATE NOCASE,BOE_YEAR,PORT_CODE COLLATE NOCASE,TAX_PERIOD,FP)CONSTRAINT UNIQUE2_ANX1_3KA UNIQUE(OBOE_NUM COLLATE NOCASE,OBOE_YEAR,OPORT_CODE COLLATE NOCASE,TAX_PERIOD,FP));"
    ],
    desc: "use this when moving from beta_v0.4 to beta_v0.5 version"
  },
  "v005": {
    offlinedb: [],
    gstindb: [],
    desc: "use this when moving from beta_v0.4 to beta_v0.5 version"
  },

};

const insertUserProfile_v01 = {
  query: "INSERT INTO USER_PROFILE (GSTIN, LGL_TRDNAME, ISSEZDEV, FILING_FREQUENCY, RETURN_TYPE, FP, TAX_PERIOD, ISACTIVE, ANX2_STAT, MTCHNG_RSLT_AVBL) VALUES (?,?,?,?,?,?,?,?,?,'Y')",
  param: ["GSTIN", "LGL_TRDNAME", "ISSEZDEV", "FILING_FREQUENCY", "RETURN_TYPE", "FP", "TAX_PERIOD", "ISACTIVE", "ANX2_STAT"]
}
const insertGstinMaster_v01 = {
  query: "INSERT INTO GSTIN_MASTER (GSTIN, LGL_TRDNAME) VALUES (?,?)",
  param: ["GSTIN", "LGL_TRDNAME"]
}


const RESTORE_GRAPH = {
  "beta_v0.1": {
    upgradableArr: ["beta_v0.2", "beta_v0.3", "beta_v0.4", "beta_v0.5", "beta_v0.6"],
    "beta_v0.2": {
      offlinedb: [...vScript["v001"].offlinedb],
      gstindb: [...vScript["v001"].gstindb],
      userProfile: [insertUserProfile_v01, insertGstinMaster_v01]
    },
    "beta_v0.3": {
      offlinedb: [...vScript["v001"].offlinedb, ...vScript["v002"].offlinedb],
      gstindb: [...vScript["v001"].gstindb, ...vScript["v002"].gstindb],
      userProfile: [insertUserProfile_v01, insertGstinMaster_v01]
    },
    "beta_v0.4": {
      offlinedb: [...vScript["v001"].offlinedb, ...vScript["v002"].offlinedb, ...vScript["v003"].offlinedb],
      gstindb: [...vScript["v001"].gstindb, ...vScript["v002"].gstindb, ...vScript["v003"].gstindb],
      userProfile: [insertUserProfile_v01, insertGstinMaster_v01]
    },
    "beta_v0.5": {
      offlinedb: [...vScript["v001"].offlinedb, ...vScript["v002"].offlinedb, ...vScript["v003"].offlinedb, ...vScript["v004"].offlinedb],
      gstindb: [...vScript["v001"].gstindb, ...vScript["v002"].gstindb, ...vScript["v003"].gstindb, ...vScript["v004"].gstindb],
      userProfile: [insertUserProfile_v01, insertGstinMaster_v01]
    },
    "beta_v0.6": {
      offlinedb: [...vScript["v001"].offlinedb, ...vScript["v002"].offlinedb, ...vScript["v003"].offlinedb, ...vScript["v004"].offlinedb, ...vScript["v005"].offlinedb],
      gstindb: [...vScript["v001"].gstindb, ...vScript["v002"].gstindb, ...vScript["v003"].gstindb, ...vScript["v004"].gstindb, ...vScript["v005"].gstindb],
      userProfile: [insertUserProfile_v01, insertGstinMaster_v01]
    }
  },
  "beta_v0.2": {
    upgradableArr: ["beta_v0.3", "beta_v0.4", "beta_v0.5", "beta_v0.6"],
    "beta_v0.3": {
      offlinedb: [...vScript["v002"].offlinedb],
      gstindb: [...vScript["v002"].gstindb],
      userProfile: [insertUserProfile_v01, insertGstinMaster_v01]
    },
    "beta_v0.4": {
      offlinedb: [...vScript["v002"].offlinedb, ...vScript["v003"].offlinedb],
      gstindb: [...vScript["v002"].gstindb, ...vScript["v003"].gstindb],
      userProfile: [insertUserProfile_v01, insertGstinMaster_v01]
    },
    "beta_v0.5": {
      offlinedb: [...vScript["v002"].offlinedb, ...vScript["v003"].offlinedb, ...vScript["v004"].offlinedb],
      gstindb: [...vScript["v002"].gstindb, ...vScript["v003"].gstindb, ...vScript["v004"].gstindb],
      userProfile: [insertUserProfile_v01, insertGstinMaster_v01]
    },
    "beta_v0.6": {
      offlinedb: [...vScript["v002"].offlinedb, ...vScript["v003"].offlinedb, ...vScript["v004"].offlinedb, ...vScript["v005"].offlinedb],
      gstindb: [...vScript["v002"].gstindb, ...vScript["v003"].gstindb, ...vScript["v004"].gstindb, ...vScript["v005"].gstindb],
      userProfile: [insertUserProfile_v01, insertGstinMaster_v01]
    }
  },

  "beta_v0.3": {
    upgradableArr: ["beta_v0.4", "beta_v0.5", "beta_v0.6"],
    "beta_v0.4": {
      offlinedb: [...vScript["v003"].offlinedb],
      gstindb: [...vScript["v003"].gstindb],
      userProfile: [insertUserProfile_v01, insertGstinMaster_v01]
    },
    "beta_v0.5": {
      offlinedb: [...vScript["v003"].offlinedb, ...vScript["v004"].offlinedb],
      gstindb: [...vScript["v003"].gstindb, ...vScript["v004"].gstindb],
      userProfile: [insertUserProfile_v01, insertGstinMaster_v01]
    },
    "beta_v0.6": {
      offlinedb: [...vScript["v003"].offlinedb, ...vScript["v004"].offlinedb, ...vScript["v005"].offlinedb],
      gstindb: [...vScript["v003"].gstindb, ...vScript["v004"].gstindb, ...vScript["v005"].gstindb],
      userProfile: [insertUserProfile_v01, insertGstinMaster_v01]
    }
  },
  "beta_v0.4": {
    upgradableArr: ["beta_v0.5","beta_v0.6"],
    "beta_v0.5": {
      offlinedb: [...vScript["v004"].offlinedb],
      gstindb: [...vScript["v004"].gstindb],
      userProfile: [insertUserProfile_v01, insertGstinMaster_v01]
    },
    "beta_v0.6": {
      offlinedb: [...vScript["v004"].offlinedb, ...vScript["v005"].offlinedb],
      gstindb: [...vScript["v004"].gstindb, ...vScript["v005"].gstindb],
      userProfile: [insertUserProfile_v01, insertGstinMaster_v01]
    }

  },
  "beta_v0.5": {
    upgradableArr: ["beta_v0.6"],
    "beta_v0.6": {
      offlinedb: [...vScript["v005"].offlinedb],
      gstindb: [...vScript["v004"].gstindb, ...vScript["v005"].gstindb],
      userProfile: [insertUserProfile_v01, insertGstinMaster_v01]
    }
  },

};

module.exports = {
  vScript: vScript,
  VERSION_HISTORY: VERSION_HISTORY,
  RESTORE_GRAPH: RESTORE_GRAPH
}